In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import hilbert

In [2]:
def cgsolve(A, b, x0, maxiters, tol):
    x = x0.copy()
    r = A @ x - b
    p = -r
    Ap = A @ p
    init_res_norm = r.T @ r
    alpha = init_res_norm / (p.T @ Ap)
    niters = 0
    while (np.sqrt(init_res_norm) / np.linalg.norm(b) > tol) and (niters < maxiters):
        niters += 1
        x += alpha * p
        r += alpha * Ap
        norm_old = init_res_norm
        init_res_norm = r.T @ r
        beta = init_res_norm / norm_old
        p = -r + beta * p
        Ap = A @ p
        alpha = init_res_norm / (p.T @ Ap)

    return x, niters, init_res_norm

allNs = [5, 8, 12, 20]
allNIters = []
for n in allNs:
    A = hilbert(n)
    b = np.ones((n, 1))
    x0 = np.zeros((n, 1))
    x, niter, init_res_norm = cgsolve(A, b, x0, 100, 1e-6)
    allNIters.append(niter)

print(allNIters, allNs)

[6, 19, 37, 68] [5, 8, 12, 20]


In [3]:
def conjugate_gradient(A, b, x_0, n, tol=1e-6, max_iters=100**6):
    r = A @ x_0 - b
    p = -r
    x_k = 0
    r_k = 0
    k = 0

    while k < max_iters and np.linalg.norm(r) > tol:
        alpha = (r.T @ r) / (p.T @ A @ p)
        x_k = x_0 + alpha * p
        r_k = r + alpha * A @ p
        beta = (r_k.T @ r_k) / (r.T @ r)
        p_k = -r_k + beta * p

        p = p_k
        r = r_k
        x_0 = x_k
        k += 1

    return x_k, r_k, k

dimensions = [5, 8, 12, 20]
iterations = []

for n in dimensions:
    A = hilbert(n)
    b = np.ones(n)
    x_0 = np.zeros(n)
    x, r, num_iter = conjugate_gradient(A, b, x_0, n)
    iterations.append(num_iter)

print(f'Num of iters: {iterations} | Corresponding dims: {dimensions}')

Num of iters: [6, 19, 38, 67] | Corresponding dims: [5, 8, 12, 20]


In [5]:
p_i = np.array([[1, 4, 7],
                [2, 1, 8],
                [3, 6, 1]])

p_j = np.array([[1, 2, 3],
                [4, 1, 6],
                [7, 8, 1]])

A = np.array([[4, 1, 1], 
              [1, 4, 1], 
              [1, 1, 4]])

print(np.all(np.linalg.eigvals(A) > 0))

#p_j^T * A * p_i
result = np.dot(p_j.T, np.dot(A, p_i))
print(result)

True
[[162 282 330]
 [150 292 266]
 [114 182 370]]
